version: '3'
services:
  node-1:
    image: my-es-node:latest
    environment:
      - NODE_NR=1
      - DISCOVERY_SEEDS=node-2:9300,node-3:9300
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9201:9201"
    expose:
      - "9201"
    volumes:
      - ./my-data/node-1-data:/data
      - ./my-data/node-1-logs:/logs
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  node-2:
    image: my-es-node:latest
    environment:
      - NODE_NR=2
      - DISCOVERY_SEEDS=node-1:9300,node-3:9300
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9202:9202"
    volumes:
      - ./my-data/node-2-data:/data
      - ./my-data/node-2-logs:/logs
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  node-3:
    image: my-es-node:latest
    environment:
      - NODE_NR=3
      - DISCOVERY_SEEDS=node-1:9300,node-2:9300
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9203:9203"
    volumes:
      - ./my-data/node-3-data:/data
      - ./my-data/node-3-logs:/logs
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536